POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Mrinmoy Mondal",
  "email": "mrinmoymondalreal@gmail.com",
  "password": "mrinmoymondal"
}

###

// Sign In
GET http://localhost:3000/auth
Content-Type: application/json
# @name auth

{
  "email": "mrinmoymondalreal@gmail.com",
  "password": "mrinmoymondal"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ODNmZjMzLTM3M2ItNDc1MS1iN2ZjLTIwMTk3OWE0YTA5YSIsImlhdCI6MTc0NDA5Nzg2MiwiZXhwIjoxNzQ0MTAxNDYyfQ.Rm2vkPW8LbMWWDZDTIa710sYOXjSMDZJsc5PTWcLodc

// Get user details
GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}

###
//Create Todo
POST http://localhost:3000/todo
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Todo 1",
  "description": "Todo 1 description",
  "completed": false
}

###

// Get all Todos
GET http://localhost:3000/todo
Authorization: Bearer {{token}}

###

// Get specific Todos with id
GET http://localhost:3000/todo/5aa7daf2-4513-4e6e-9942-0273e75c7a12
Authorization: Bearer {{token}}